#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: runt seed --prod"
	echo "       runt seed <path-to-dump-file>"
elif [ "$1" == "--prod" ]; then
	echo "Fetching latest dump from production..."
	ssh coinflipper.org cat "~/backups/login/login.dump" | \
		docker exec -i login-mongo mongorestore --drop --archive
else
	echo "Restoring from $1..."
	docker exec -i login-mongo mongorestore --drop --archive < "$1"
fi
